var date = new Date()
console.log(date)
console.log(date.toDateString())
console.log(date.toTimeString())
console.log(date.toLocaleTimeString())
console.log(date.getFullYear())
console.log(date.getMonth())
console.log(date.getMinutes())
console.log(date.getHours())
console.log(date.getSeconds())
console.log(date.getMilliseconds())
